name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed # Triggers when the referenced workflow completes (successfully or not)
      
jobs:
  CD:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only run if the preceding workflow concluded successfully
    environment: dev
    steps:
      - name: Download artifacts
        run: echo "Download artifacts"

      - name: Deploy to Server
        run: echo "Deploying application to server"
