name: CI pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.9'

      - name: Run Hello World Python
        run: python hello.py
      
      - name: Build Docker Image
        run: |
          docker build -t hello-python-app . 
          docker images
          
      - name: Run Docker Container
        run: docker run hello-python-app
          

      - name: Run tests
        run: echo "running application tests"

      - name: Sonar scanning
        run: echo "running sonar scans for SAST"

  CD-dev:
    runs-on: ubuntu-latest
    needs: CI
    environment: dev
    steps:
      - name: Download artifacts
        run: echo "Download artifacts"

      - name: Deploy to Server
        run: echo "Deploying application to server"
        
  CD-prod:
    runs-on: ubuntu-latest
    needs: CD-dev
    environment: prod
    steps:
      - name: Download artifacts
        run: echo "Download artifacts"

      - name: Deploy to Server
        run: echo "Deploying application to server"
